name: Generate YAML changelog
description: Generates a machine-readable changelog.yaml file from multiple sources, including bot commits and the Unreleased section of CHANGELOG.md
inputs:
  yaml:
    description: Path to changelog.yaml, will be overwritten
    required: false
    default: changelog.yaml
  markdown:
    description: Path to CHANGELOG.md to source entries from (read-only)
    required: false
    default: CHANGELOG.md
  renovate:
    description: Extract dependency updates from renovate commits
    required: false
    default: "true"
  dependabot:
    description: Extract dependency updates from dependabot commits
    required: false
    default: "true"
  git-root:
    description: Path to the root of the git repository to source bot commits from
    required: false
    default: "."
  tag-prefix:
    description: Find commits since latest matching this prefix
    required: false
    default: ""
  included-dirs:
    description: Only scan commits scoping at least one file in any of the following comma-separated directories
    required: false
    default: ""
  excluded-dirs:
    description: Exclude commits whose changes only impact files in specified dirs relative to repository root
    required: false
    default: ""
  exit-code:
    description: Exit code if changelog is empty
    required: false
    default: "1"
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - generate-yaml
    - --markdown
    - ${{ inputs.markdown }}
    - --renovate=${{ inputs.renovate }}
    - --dependabot=${{ inputs.dependabot }}
    - --git-root
    - ${{ inputs.git-root }}
    - --tag-prefix
    - ${{ inputs.tag-prefix }}
    - --included-dirs=${{ inputs.included-dirs }}
    - --excluded-dirs=${{ inputs.excluded-dirs }}
    - --exit-code
    - ${{ inputs.exit-code }}
