name: Validate Changelog
description: Validates and prints errors if changelog has an invalid format
inputs:
  markdown:
    description: Path to CHANGELOG.md to update
    required: false
    default: CHANGELOG.md
  exit-code:
    description: Exit code when errors are found
    required: false
    default: "1"
outputs:
  valid:
    description: Returns `true` if the changelog is valid
runs:
  using: docker
  image: ../Dockerfile
  args:
    - validate-changelog
    - --markdown
    - ${{ inputs.markdown }}
    - --exit-code
    - ${{ inputs.exit-code }}
