name: Link Changelog
description: Tries to add links to the original changelog.yml for all its dependencies
inputs:
  yaml:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
  dictionary:
    description: Link dependency changelogs with the mappings in this dictionary
    required: false
    default: ""
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - link-changelog
    - --dictionary
    - ${{ inputs.dictionary }}
